name: Build Jekyll Site in /src/html/
on:
  push:
    branches:
      - main  # Change if using a different branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Jekyll & Bundler
        run: gem install jekyll bundler

      - name: Install Minima Theme
        run: gem install minima  # 🔹 This installs the missing theme

      - name: Build Jekyll
        run: jekyll build --source src/html --destination _site  # 🔹 Using _site as output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
